name: GitHub Pages

on:
  push:
    branches:
      - root
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd certificate-policy
          make

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/root'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./certificate-policy/build